// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"latihan/controller"
	"latihan/database"
	"latihan/library"
	middlewaree "latihan/middleware"
	"latihan/repository"
	"latihan/service"

	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeService() (*controller.Controller, *sql.DB, *middlewaree.Middlewaree, *zap.Logger) {
	log := library.InitLog()
	db, err := database.ConnectDB()
	if err != nil {
		log.Error("Databaes Error : ", zap.Error(err))
		return nil, nil, nil, nil
	}
	
	repository := repository.NewRepository(db, log)
	serviceService := service.NewService(repository, log)
	Controller := controller.NewController(serviceService, log)
	if Controller == nil{
		return nil, nil, nil, nil
	}
	
	mid := middlewaree.NewMiddleware(log, serviceService)
	
	return Controller, db, mid, log
}
